[package]
name = "tsc_c"
version = "0.1.0"
edition = "2021"

[dependencies]
cty = "0.2.2"
ssc = { path = "../ssc" }
tsc = { path = "../tsc" }

[lib]
crate-type = ["cdylib"]
name = "TSC"
path = "src/lib.rs"
